### ISSUE TITLE
Support negative delay

### ISSUE THREAD

**Issue by danfarrow** [tomlum/OneMoreTry#1]
:exploding_head: :exploding_head:  :exploding_head: 

I love this app - it's so simple but rich with possibilities :+1:

**Comment by tomlum** [comment]
Ah!! Thanks so much!!

Can I ask what you mean by negative delay?  Wouldn't that mean... seeing into the future?

**Comment by danfarrow** [comment]
Yes, sorry. Probably asking too much. But fun to imagine!

**Comment by danfarrow** [comment]
![one-more-try](https://user-images.githubusercontent.com/236580/97080425-0af50c80-15f3-11eb-868d-224d07671443.gif)
_Hat tip to [Ted Chiang](https://www.nature.com/articles/436150a)!_
